[toolchain]

[workspace]
members = [
    "programs/modules/geo_restrict_module",
    "programs/modules/kyc_module",
    "programs/modular_compliance",
    "programs/token_program",
]

[features]
resolution = true
skip-lint = false

[programs.localnet]
geo_restrict_module = "HYd7fRvoLw6nxVVZuUsnVy6w8aDDrhUpznCkTQL2D3RY"
kyc_module = "93r3snAcjiLiAkjN3yNdqgxnhbetVGMm4rGrxPSkdbft"
modular_compliance = "78ZVaqUpKoWduqWujw5HqFWi77qsTSLnpq3TMvbtbLyN"
token_program = "4u4wGUQDzFFh7Hnnk2wt8SN3HkhfcFbRfUyvnjxkTkn8"
token_metadata_program = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallets/phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test.spec.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
