[toolchain]

[workspace]
members = [
    "programs/geo_restrict_module",
    "programs/kyc_module",
    "programs/modular_compliance",
]

[features]
resolution = true
skip-lint = false

[programs.localnet]
modular_compliance = "EBrwd8JEmXP2M4YRbhdTP1zuSj4cm9W4MzMNf6eMAUAA"
kyc_module = "BXGeVsqLrbTQ7dPAd1a12bA7zuewNKHi3rPpaF7qWov7"
geo_restrict_module = "scBwKWSo8RN9VHM629PWSu9kPGDaRzBZgqYQSEoipfe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallets/phantom-keypair.json"

# [scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
