[toolchain]

[workspace]
members = [
    "programs/geo_restrict_module",
    "programs/kyc_module",
    "programs/modular_compliance",
]


[features]
resolution = true
skip-lint = false

[programs.localnet]
modular_compliance = "5rmJys67owCbWQht5C6sRw7F8g8mDhjzhhjrhuLiQkdP"
kyc_module = ""
geo_restrict_module = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallets/phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
